// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function Counter(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return React.createElement(React.Fragment, undefined, React.createElement("h3", undefined, String(match[0])), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (prev) {
                                    return prev + 1 | 0;
                                  }));
                    })
                }, "Increment"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (prev) {
                                    return prev - 1 | 0;
                                  }));
                    })
                }, "Decrement"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (param) {
                                    return 0;
                                  }));
                    })
                }, "Reset"), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("button", {
                  onClick: (function (param) {
                      return RescriptReactRouter.push("zoo");
                    })
                }, "Go to zoo"));
}

var make = Counter;

export {
  make ,
  
}
/* react Not a pure module */
