// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nav from "../components/nav/Nav.bs.js";
import * as React from "react";

function Form(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Nav.make, {}), React.createElement("h1", undefined, "Form page"));
}

var make = Form;

export {
  make ,
  
}
/* Nav Not a pure module */
