// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zoo from "./components/zoo/Zoo.bs.js";
import * as React from "react";

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Zoo.make, {}));
}

var make = App;

export {
  make ,
  
}
/* Zoo Not a pure module */
