// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Counter from "./components/Counter.bs.js";

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Hello World"), React.createElement(Counter.make, {}));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
