// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Form from "./pages/Form.bs.js";
import * as About from "./pages/About.bs.js";
import * as Index from "./pages/Index.bs.js";
import * as React from "react";
import * as FourOhFour from "./pages/FourOhFour.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return React.createElement(Index.make, {});
  }
  switch (match.hd) {
    case "about" :
        if (!match.tl) {
          return React.createElement(About.make, {});
        }
        break;
    case "form" :
        if (!match.tl) {
          return React.createElement(Form.make, {});
        }
        break;
    default:
      
  }
  return React.createElement(FourOhFour.make, {});
}

var make = App;

export {
  make ,
  
}
/* Form Not a pure module */
