// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function SelectedAnimalHeader(Props) {
  var description = Props.description;
  return React.createElement("h3", undefined, "Selected animal is " + description);
}

var make = SelectedAnimalHeader;

export {
  make ,
  
}
/* react Not a pure module */
