// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as SelectedAnimalHeader from "./SelectedAnimalHeader.bs.js";

import './zoo.css'
;

var state = {
  selectedAnimal: undefined
};

function reducer(state, action) {
  return {
          selectedAnimal: action._0
        };
}

function getInformation(a) {
  if (typeof a === "number") {
    return "The animal is Zebra";
  } else if (a.TAG === /* Giraffe */0) {
    return "The giraffe is " + String(a._0) + " feet tall";
  } else {
    return "The dog is " + (
            a._0 === true ? "is" : "is not"
          ) + " barking";
  }
}

function getAnimalString(a) {
  if (a !== undefined) {
    return getInformation(a);
  } else {
    return "No animals";
  }
}

function Zoo(Props) {
  var match = React.useReducer(reducer, state);
  var dispatch = match[1];
  return React.createElement(React.Fragment, undefined, React.createElement(SelectedAnimalHeader.make, {
                  description: getAnimalString(match[0].selectedAnimal)
                }), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* AnimalSelected */{
                                  _0: /* Zebra */0
                                });
                    })
                }, "Select Zebra"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* AnimalSelected */{
                                  _0: {
                                    TAG: /* Giraffe */0,
                                    _0: 10
                                  }
                                });
                    })
                }, "Select Giraffe"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* AnimalSelected */{
                                  _0: {
                                    TAG: /* Dog */1,
                                    _0: true
                                  }
                                });
                    })
                }, "Select Dog"));
}

var make = Zoo;

export {
  state ,
  reducer ,
  getInformation ,
  getAnimalString ,
  make ,
  
}
/*  Not a pure module */
