// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import NavModuleCss from "./Nav.module.css";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

var styles = NavModuleCss;

function Nav(Props) {
  return React.createElement("div", {
              className: styles.wrapper
            }, React.createElement("div", {
                  className: styles.link,
                  onClick: (function (param) {
                      return RescriptReactRouter.push("/");
                    })
                }, "Home"), React.createElement("div", {
                  className: styles.link,
                  onClick: (function (param) {
                      return RescriptReactRouter.push("about");
                    })
                }, "About"), React.createElement("div", {
                  className: styles.link,
                  onClick: (function (param) {
                      return RescriptReactRouter.push("form");
                    })
                }, "Form"));
}

var make = Nav;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
